Modification in some functionality and solved some minor bugs.
applibgroup/XRadarView pull request #5
Opened 2021-08-25 07:22 UTC by Click2cloud-Eros

**What type of PR is this?**
1) bug fix
2) enhancement

**What this PR does / why we need it?**
This PR included some modification and bugs fixes.

**Which modification and issue(s) this PR fixes:** 
1) Merge some array attributes (i.e. titles, drawables, values, percents, colors) into single ArrayList attribute (i.e. NodeList).
2) Add **enabledMultiColorRegion** and **enabledCircularOutline** attribute for xml.
3) Solved last button cut issue.
4) Solved setCount issue.
5) Change functionality of **Load Animation** button.
6) Add and remove Junit testcases as per new implementation.
7) Update readme file content as per new implementation.

2021-09-13 09:15 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/applibgroup/XRadarView?pullRequest=5) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/applibgroup/XRadarView?pullRequest=5) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/applibgroup/XRadarView?pullRequest=5) it.</sub>

2021-09-28 11:00 UTC, kanaksony commented on xradar/src/main/java/com/orzangleli/radar/XRadarView.java
>      private Color startColor = new Color(RgbPalette.parse("#80FF0000"));
Please move this in resources

2021-09-28 11:29 UTC, kanaksony requested changes
Please add Copyright for new code files.
Add colors code in resources instead of code.
Utils.java# getPathById() shall be optimized like - 
 public static String getPathById(Context context, int id) {
        if (context != null) {
            ResourceManager manager = context.getResourceManager();
            if (manager != null) {
                try {
                    return manager.getMediaPath(id);
                } catch (IOException | NotExistException | WrongTypeException e) {
                    //TO-DO: Handle exception and log error here
                    return "";
                }
            }
        }
        return "";
    }

Node - There are some methods never called

2021-09-28 12:29 UTC, Click2cloud-Eros commented
> Please add Copyright for new code files. Add colors code in resources instead of code. Utils.java# getPathById() shall be optimized like - ` public static String getPathById(Context context, int id) { if (context != null) { ResourceManager manager = context.getResourceManager(); if (manager != null) { try { return manager.getMediaPath(id); } catch (IOException | NotExistException | WrongTypeException e) { //TO-DO: Handle exception here return ""; } } } return ""; }`
> 
> Node - There are some methods never called

I seen, I have already added copyright in new files.
And other changes I will do.

2021-09-30 15:47 UTC, kanaksony approved these changes
Looks good

2021-10-12 07:44 UTC, kanaksony approved these changes

2021-10-13 06:20 UTC, sharathks84 approved these changes
Okay Approved

2021-10-13 09:39 UTC, applibengineering approved these changes

2022-01-18 08:10 UTC, merged